# Generated by Django 2.1.7 on 2019-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhym_news',
            name='news_count',
            field=models.BigIntegerField(),
        ),
    ]
