# Generated by Django 2.1.7 on 2019-11-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20191121_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dhym_news',
            name='news_image',
            field=models.ImageField(blank=True, max_length=128, null=True, upload_to='news'),
        ),
    ]
