# Generated by Django 2.2.7 on 2019-11-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dhym_Baner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baner_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/main-slider')),
                ('baner_describe', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'dhym_baner',
            },
        ),
        migrations.CreateModel(
            name='dhym_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('data_title', models.CharField(blank=True, max_length=32, null=True)),
                ('data_number', models.IntegerField(blank=True, max_length=7, null=True)),
                ('data_describe', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'dhym_data',
            },
        ),
        migrations.CreateModel(
            name='dhym_introductionPatent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introductionPatent_name', models.CharField(blank=True, max_length=48, null=True)),
                ('introductionPatent_count', models.IntegerField(blank=True, max_length=4, null=True)),
            ],
            options={
                'db_table': 'dhym_introductionPatent',
            },
        ),
        migrations.CreateModel(
            name='dhym_manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(blank=True, max_length=32, null=True)),
                ('manager_address', models.CharField(blank=True, max_length=32, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('manager_email', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'dhym_manager',
            },
        ),
        migrations.CreateModel(
            name='dhym_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(blank=True, max_length=32, null=True)),
                ('message_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('message_email', models.CharField(blank=True, max_length=32, null=True)),
                ('message_content', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dhym_message',
            },
        ),
        migrations.CreateModel(
            name='dhym_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('news_title', models.CharField(blank=True, max_length=48, null=True)),
                ('news_count', models.IntegerField(blank=True, max_length=11, null=True)),
                ('news_time', models.DateTimeField(auto_now_add=True)),
                ('news_describe', models.CharField(blank=True, max_length=128, null=True)),
                ('news_one_describe', models.CharField(blank=True, max_length=255, null=True)),
                ('news_one_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('news_two_describe', models.CharField(blank=True, max_length=255, null=True)),
                ('news_two_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('news_three_describe', models.CharField(blank=True, max_length=255, null=True)),
                ('news_three_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('news_four_describe', models.CharField(blank=True, max_length=255, null=True)),
                ('news_four_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('news_five_describe', models.CharField(blank=True, max_length=255, null=True)),
                ('news_five_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('news_sex_describe', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dhym_news',
            },
        ),
        migrations.CreateModel(
            name='dhym_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small_title', models.CharField(blank=True, max_length=12, null=True)),
                ('title_big_title', models.CharField(blank=True, max_length=24, null=True)),
                ('title_us_title', models.CharField(blank=True, max_length=48, null=True)),
                ('title_describe', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dhym_title',
            },
        ),
        migrations.CreateModel(
            name='dhym_video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_fifle', models.FileField(blank=True, null=True, upload_to='video')),
                ('video_ch', models.CharField(blank=True, max_length=48, null=True)),
                ('video_us', models.CharField(blank=True, max_length=96, null=True)),
            ],
            options={
                'db_table': 'dhym_video',
            },
        ),
        migrations.CreateModel(
            name='dhym_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('team_us', models.CharField(blank=True, max_length=32, null=True)),
                ('team_position', models.CharField(blank=True, max_length=32, null=True)),
                ('team_dhym_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.dhym_title')),
            ],
            options={
                'db_table': 'dhym_team',
            },
        ),
        migrations.CreateModel(
            name='dhym_support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_title', models.CharField(blank=True, max_length=48, null=True)),
                ('support_describe', models.CharField(blank=True, max_length=128, null=True)),
                ('support_dhym_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.dhym_title')),
            ],
            options={
                'db_table': 'dhym_support',
            },
        ),
        migrations.CreateModel(
            name='dhym_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('service_type', models.CharField(blank=True, max_length=48, null=True)),
                ('service_descride', models.CharField(blank=True, max_length=128, null=True)),
                ('service_dhym_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.dhym_title')),
            ],
            options={
                'db_table': 'dhym_service',
            },
        ),
        migrations.CreateModel(
            name='dhym_requirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements_title', models.CharField(blank=True, max_length=48, null=True)),
                ('requirements_describe', models.CharField(blank=True, max_length=128, null=True)),
                ('requirements_dhym_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.dhym_title')),
            ],
            options={
                'db_table': 'dhym_requirements',
            },
        ),
        migrations.CreateModel(
            name='dhym_ProductAdvantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productAdvantage_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/icons')),
                ('productAdvantage_zh', models.CharField(blank=True, max_length=48, null=True)),
                ('productAdvantage_us', models.CharField(blank=True, max_length=48, null=True)),
                ('productAdvantage_descride', models.CharField(blank=True, max_length=255, null=True)),
                ('productAdvantage_dhym_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.dhym_title')),
            ],
            options={
                'db_table': 'dhym_ProductAdvantage',
            },
        ),
        migrations.CreateModel(
            name='dhym_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/icons')),
                ('process_title', models.CharField(blank=True, max_length=48, null=True)),
                ('process_describe', models.CharField(blank=True, max_length=128, null=True)),
                ('process_dhym_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.dhym_title')),
            ],
            options={
                'db_table': 'dhym_process',
            },
        ),
        migrations.CreateModel(
            name='dhym_partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/clients')),
                ('partners_dhym_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.dhym_title')),
            ],
            options={
                'db_table': 'dhym_partners',
            },
        ),
        migrations.CreateModel(
            name='dhym_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_title', models.CharField(blank=True, max_length=128, null=True)),
                ('history_describe', models.CharField(blank=True, max_length=128, null=True)),
                ('history_time', models.DateField(auto_now=True)),
                ('history_dhym_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.dhym_title')),
            ],
            options={
                'db_table': 'dhym_history',
            },
        ),
        migrations.CreateModel(
            name='dhym_Companyprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyprofile_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('Companyprofile_describe_big', models.CharField(blank=True, max_length=128, null=True)),
                ('Companyprofile_describe_small', models.CharField(blank=True, max_length=128, null=True)),
                ('Companyprofile_dhym_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.dhym_title')),
            ],
            options={
                'db_table': 'dhym_Companyprofile',
            },
        ),
        migrations.CreateModel(
            name='dhym_Chooseus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chooseus_zh', models.CharField(blank=True, max_length=48, null=True)),
                ('Chooseus_us', models.CharField(blank=True, max_length=48, null=True)),
                ('Chooseus_describe', models.CharField(blank=True, max_length=255, null=True)),
                ('Chooseus_dhym_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.dhym_title')),
            ],
            options={
                'db_table': 'dhym_Chooseus',
            },
        ),
        migrations.CreateModel(
            name='dhym_certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_img', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/clients')),
                ('certificate_dhym_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.dhym_title')),
            ],
            options={
                'db_table': 'dhym_certificate',
            },
        ),
    ]
