# Generated by Django 2.2.7 on 2019-11-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dhym_Pureimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pureimage_one', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('pureimage_two', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('pureimage_three', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
                ('pureimage_four', models.ImageField(blank=True, max_length=128, null=True, upload_to='images/resource')),
            ],
            options={
                'db_table': 'dhym_Pureimage',
            },
        ),
    ]
